version: "3.3"
services:

  db:
    env_file:
      - .env
    container_name: mlflow_db
    image: postgres
    volumes:
      - db_volume:/var/lib/postgresql/data
    restart: always
    expose:
      - "5432"
    networks:
      - mlflow_internal

  mlflow:
    env_file:
      - .env
    container_name: tracker_mlflow
    image: tracker_ml
    restart: unless-stopped
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./mlartifacts:/mlartifacts
    networks:
      - mlflow_public
      - mlflow_internal
    entrypoint: bash ./wait-for-it.sh db:5432 -t 90 -- mlflow server --backend-store-uri postgresql//${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB} --artifacts-destination /mlartifacts --serve-artifacts -h 0.0.0.0

networks:
  mlflow_internal:
  mlflow_public:
    driver: bridge

volumes:
  db_volume:

